# DockerFile.frontend
FROM node:22-alpine AS build
WORKDIR /usr/src/app
COPY j-jobs_frontend/. .
RUN yarn install --frozen-lockfile --ignore-scripts
RUN yarn build --configuration production

FROM nginx:1.27-alpine
COPY conteneurisation/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/j-jobs_frontend/browser/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]